accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.AuthUserView.as_view(), name='auth'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.UserProfile.as_view(), name='profile'),
    path('profile/change/', views.ChangeProfileView.as_view(), name='profile_change')
]

config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve 

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('quiz/', include('quiz.urls')),
    path('about/', include('common.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('student/dashboard/<str:telegram_id>/', views.StudentDashboardView.as_view(), name='student_dashboard'),
    path('course/<slug:course_slug>/', views.CourseDetailView.as_view(), name='course_detail'),
    path("course/lesson/<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/", views.LessonDetailView.as_view(), name="lesson_detail"),
    path('qa/admin/', views.QuestionAnswerAdmin.as_view(), name='qaAdmin'),
    path('question/delete/<int:question_id>/', views.delete_question, name='delete_question'),
    path('answer/to/question/<int:question_id>/', views.AnswerTheQuestion.as_view(), name='answer_to_question'),
    path('rating/', views.RatingView.as_view(), name='rating'),
    path("assignments/<slug:course_slug>/<slug:module_slug>", views.FileLessonView.as_view(), name="assignments")
]

templates/includes/footer.html
<footer class="bg-darkblack">
    <div class="container pt-65px pb-5 lg:pb-10">
      

      <!-- footer copyright  -->
      <div>
        <div
          class="grid grid-cols-1 lg:grid-cols-12 gap-5 lg:gap-30px pt-10 items-center"
        >
          <div class="lg:col-start-1 lg:col-span-3">
            <a href="#">
              <img src="assets/images/logo/logo_2.png" alt="" >
            </a>
          </div>

          <div class="lg:col-start-4 lg:col-span-6">
            <p class="text-whiteColor">
              Copyright © <span class="text-primaryColor">2025 </span> by
              Mukhriddin. All Rights Reserved.
            </p>
          </div>

          <div class="lg:col-start-10 lg:col-span-3">
            <ul class="flex gap-3 lg:gap-2 2xl:gap-3 lg:justify-end">
              <li>
                <a
                  href="https://www.facebook.com/muhriddin.ahtamqulov.1"
                  class="w-40.19px lg:w-35px 2xl:w-40.19px h-37px lg:h-35px 2xl:h-37px leading-37px lg:leading-35px 2xl:leading-37px text-whiteColor bg-whiteColor bg-opacity-10 hover:bg-primaryColor text-center"
                  ><i class="icofont-facebook"></i
                ></a>
              </li>
              <li>
                <a
                  href="#"
                  class="w-40.19px lg:w-35px 2xl:w-40.19px h-37px lg:h-35px 2xl:h-37px leading-37px lg:leading-35px 2xl:leading-37px text-whiteColor bg-whiteColor bg-opacity-10 hover:bg-primaryColor text-center"
                  ><i class="icofont-instagram"></i
                ></a>
              </li>
              <li>
                <a
                  href="#"
                  class="w-40.19px lg:w-35px 2xl:w-40.19px h-37px lg:h-35px 2xl:h-37px leading-37px lg:leading-35px 2xl:leading-37px text-whiteColor bg-whiteColor bg-opacity-10 hover:bg-primaryColor text-center"
                  ><i class="icofont-vimeo"></i
                ></a>
              </li>
              <li>
                <a
                  href="#"
                  class="w-40.19px lg:w-35px 2xl:w-40.19px h-37px lg:h-35px 2xl:h-37px leading-37px lg:leading-35px 2xl:leading-37px text-whiteColor bg-whiteColor bg-opacity-10 hover:bg-primaryColor text-center"
                  ><i class="icofont-linkedin"></i
                ></a>
              </li>
              <li>
                <a
                  href="https://www.youtube.com/@muhriddinahtamqulov9277"
                  class="w-40.19px lg:w-35px 2xl:w-40.19px h-37px lg:h-35px 2xl:h-37px leading-37px lg:leading-35px 2xl:leading-37px text-whiteColor bg-whiteColor bg-opacity-10 hover:bg-primaryColor text-center"
                  ><i class="icofont icofont-youtube-play"></i
                ></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/includes/lesson-left.html
{% load progress_tags %}
<div class="xl:col-start-1 xl:col-span-4" data-aos="fade-up">
    <!-- curriculum -->
    <ul class="accordion-container curriculum">
      <!-- accordion -->
       {% for module in modules %}
       {% if forloop.first %}
      <li class="accordion mb-25px overflow-hidden active">
        <div
          class="bg-whiteColor border border-borderColor dark:bg-whiteColor-dark dark:border-borderColor-dark rounded-t-md"
        >
          <!-- controller -->
          <div>
            <button
              class="accordion-controller flex justify-between items-center text-xl text-headingColor font-bold w-full px-5 py-18px dark:text-headingColor-dark font-hind leading-[20px]"
            >
              <span>{{ module.name }}</span>

              <svg
                class="transition-all duration-500 rotate-0"
                width="20"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 16 16"
                fill="#212529"
              >
                <path
                  fill-rule="evenodd"
                  d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"
                ></path>
              </svg>
            </button>
          </div>
          <!-- content -->
           
          <div class="accordion-content transition-all duration-500">
            <div class="content-wrapper p-10px md:px-30px">
              <ul>
                {% for lesson in module.lesson_set.all %}
                {% get_user_progress lesson request.user as progress %}
                {% get_first_quiz as first_quiz %}
                {% if forloop.first %}
                <li class="py-4 flex items-center justify-between flex-wrap border-b border-borderColor dark:border-borderColor-dark">
                  <div>
                    <h4 class="text-blackColor dark:text-blackColor-dark leading-1 font-light">
                      <i class="icofont-audio mr-10px"></i>
                      {{ first_quiz.title }}
                    </h4>
                  </div>
                  <div class="text-blackColor dark:text-blackColor-dark text-sm flex items-center">
                
                    
                    <a href="{% url 'quiz_details' course_slug first_quiz.id %}" class="bg-primaryColor text-whiteColor text-sm ml-5 rounded py-0.5">
                      <p class="px-10px">
                         Ko'rish
                      </p>
                    </a>
                  </div>
                </li>
                {% endif %}
                <li
                  class="py-4 flex items-center justify-between flex-wrap border-b border-borderColor dark:border-borderColor-dark"
                >
                  <div>
                    <h4
                      class="text-blackColor dark:text-blackColor-dark leading-1 font-light"
                    >
                      <i class="icofont-video-alt mr-10px"></i>
                      <a
                        href="#"
                        class="font-medium text-contentColor dark:text-contentColor-dark hover:text-primaryColor dark:hover;text-primaryColor"
                        >{{ lesson.title }}
                      </a>
                    </h4>
                  </div>
                  <div
                    class="text-blackColor dark:text-blackColor-dark text-sm flex items-center"
                  >
                    
                    {% if progress and progress.is_open %}
                    <p class="font-semibold">{{ lesson.minutes }} min</p>
                    <a
                      href="{{ lesson.get_link }}"
                      class="bg-primaryColor text-whiteColor text-sm ml-5 rounded py-0.5"
                    >
                      <p class="px-10px">
                        <i class="icofont-eye"></i> Ko'rish
                      </p>
                    </a>
                    {% else %}
                    <div class="text-contentColor dark:text-contentColor-dark text-sm">
                      <p>
                        <i class="icofont-lock"></i>
                      </p>
                    </div>
                    {% endif %}
                  </div>
                </li>
                {% if lesson.myquiz %}
                <li class="py-4 flex items-center justify-between flex-wrap border-b border-borderColor dark:border-borderColor-dark">
                  <div>
                    <h4 class="text-blackColor dark:text-blackColor-dark leading-1 font-light">
                      <i class="icofont-audio mr-10px"></i>
                      {{ lesson.myquiz.title }}
                    </h4>
                  </div>
                  <div class="text-blackColor dark:text-blackColor-dark text-sm flex items-center">
                
                    {% if progress.is_open and lesson.myquiz.is_open %}
                    <a href="{% url 'quiz_details' lesson.module.course.slug lesson.myquiz.id %}" class="bg-primaryColor text-whiteColor text-sm ml-5 rounded py-0.5">
                      <p class="px-10px">
                         Ko'rish
                      </p>
                    </a>
                    {% else %}
                    <div class="text-contentColor dark:text-contentColor-dark text-sm">
                      <p>
                        <i class="icofont-lock"></i>
                      </p>
                    </div>
                    {% endif %}
                  </div>
                </li>
                {% endif %}
                {% endfor %}
                <li
                  class="py-4 flex items-center justify-between flex-wrap"
                >
                  <div>
                    <h4
                      class="text-blackColor dark:text-blackColor-dark leading-1 font-light"
                    >
                      <i class="icofont-file-text mr-10px"></i>
                      <a
                        href="{% url 'main:assignments' module.course.slug module.slug %}"
                        class="font-medium text-contentColor dark:text-contentColor-dark hover:text-primaryColor dark:hover;text-primaryColor"
                        >Materiallar
                      </a>
                    </h4>
                  </div>
                </li>
              </ul>
            </div>
          </div>
          
        </div>
      </li>
      {% else %}
      <li class="accordion mb-25px overflow-hidden">
        <div
          class="bg-whiteColor border border-borderColor dark:bg-whiteColor-dark dark:border-borderColor-dark"
        >
          <!-- controller -->
          <div>
            <button
              class="accordion-controller flex justify-between items-center text-xl text-headingColor font-bold w-full px-5 py-18px dark:text-headingColor-dark font-hind leading-[20px]"
            >
              <span>{{ module.name }}</span>

              <svg
                class="transition-all duration-500 rotate-0"
                width="20"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 16 16"
                fill="#212529"
              >
                <path
                  fill-rule="evenodd"
                  d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"
                ></path>
              </svg>
            </button>
          </div>
          <!-- content -->
          <div
            class="accordion-content transition-all duration-500 h-0"
          >
            <div class="content-wrapper p-10px md:px-30px">
              <ul>
                {% for lesson in module.lesson_set.all %}
                {% get_user_progress lesson request.user as progress %}
                <li
                  class="py-4 flex items-center justify-between flex-wrap border-b border-borderColor dark:border-borderColor-dark"
                >
                  <div>
                    <h4
                      class="text-blackColor dark:text-blackColor-dark leading-1 font-light"
                    >
                      <i class="icofont-video-alt mr-10px"></i>
                      <a
                        href="#"
                        class="font-medium text-contentColor dark:text-contentColor-dark hover:text-primaryColor dark:hover;text-primaryColor"
                        >{{ lesson.title }}
                      </a>
                    </h4>
                  </div>
                  <div
                    class="text-blackColor dark:text-blackColor-dark text-sm flex items-center"
                  >
                    
                    {% if progress.is_open %}
                    <p class="font-semibold">{{ lesson.minutes }} min</p>
                    <a
                      href="{{ lesson.get_link }}"
                      class="bg-primaryColor text-whiteColor text-sm ml-5 rounded py-0.5"
                    >
                      <p class="px-10px">
                        <i class="icofont-eye"></i> Ko'rish
                      </p>
                    </a>
                    {% else %}
                    <div class="text-contentColor dark:text-contentColor-dark text-sm">
                      <p>
                        <i class="icofont-lock"></i>
                      </p>
                    </div>
                    {% endif %}
                  </div>
                </li>
                {% if lesson.myquiz %}
                <li class="py-4 flex items-center justify-between flex-wrap border-b border-borderColor dark:border-borderColor-dark">
                  <div>
                    <h4 class="text-blackColor dark:text-blackColor-dark leading-1 font-light">
                      <i class="icofont-audio mr-10px"></i>
                      {{ lesson.myquiz.title }}
                    </h4>
                  </div>
                  <div class="text-blackColor dark:text-blackColor-dark text-sm flex items-center">
                
                    {% if lesson.myquiz.is_open %}
                    <a href="{% url 'my_quiz' lesson.module.course.slug lesson.myquiz.id %}" class="bg-primaryColor text-whiteColor text-sm ml-5 rounded py-0.5">
                      <p class="px-10px">
                         Boshlash
                      </p>
                    </a>
                    {% else %}
                    <div class="text-contentColor dark:text-contentColor-dark text-sm">
                      <p>
                        <i class="icofont-lock"></i>
                      </p>
                    </div>
                    {% endif %}
                  </div>
                </li>
                {% endif %}
                {% endfor %}
                <li
                  class="py-4 flex items-center justify-between flex-wrap"
                >
                  <div>
                    <h4
                      class="text-blackColor dark:text-blackColor-dark leading-1 font-light"
                    >
                      <i class="icofont-file-text mr-10px"></i>
                      <a
                        href="{% url 'main:assignments' module.course.slug module.slug %}"
                        class="font-medium text-contentColor dark:text-contentColor-dark hover:text-primaryColor dark:hover;text-primaryColor"
                        >Materiallar
                      </a>
                    </h4>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </li>
      {% endif %}
      {% endfor %}
    </ul>
  </div>

templates/includes/profile_left.html
<div class="lg:col-start-1 lg:col-span-3">
    <!-- navigation menu -->
    <div
      class="p-30px pt-5 lg:p-5 2xl:p-30px 2xl:pt-5 rounded-lg2 shadow-accordion dark:shadow-accordion-dark bg-whiteColor dark:bg-whiteColor-dark"
    >
      <!-- greeting -->
      <h5
        class="text-sm leading-1 font-semibold uppercase text-contentColor dark:text-contentColor-dark bg-lightGrey5 dark:bg-whiteColor-dark p-10px pb-7px mt-5 mb-10px"
      >
        XUSH KELIBSIZ, {{ request.user.get_full_name }}
      </h5>
      {% if request.user.user_type == 'TEACHER' %}
      <ul>
        <li
          class="py-10px border-b border-borderColor dark:border-borderColor-dark"
        >
          <a
            href="#"
            class="text-contentColor dark:text-contentColor-dark hover:text-primaryColor dark:hover:text-primaryColor leading-1.8 flex gap-3 text-nowrap"
            ><svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="feather feather-home"
            >
              <path
                d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"
              ></path>
              <polyline points="9 22 9 12 15 12 15 22"></polyline>
            </svg>
            Dashboard</a
          >
        </li>
        <li
          class="py-10px border-b border-borderColor dark:border-borderColor-dark"
        >
          <a
            href="{% url 'accounts:profile' %}"
            class="text-primaryColor hover:text-primaryColor dark:hover:text-primaryColor leading-1.8 flex gap-3 text-nowrap"
            ><svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="feather feather-user"
            >
              <path
                d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"
              ></path>
              <circle cx="12" cy="7" r="4"></circle>
            </svg>
            Mening Profilim</a
          >
        </li>
        <li class="py-10px border-b border-borderColor dark:border-borderColor-dark">
          <a href="{% url 'main:qaAdmin' %}"
            class="text-contentColor dark:text-contentColor-dark hover:text-primaryColor dark:hover:text-primaryColor leading-1.8 flex gap-3 text-nowrap">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor"
              stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-message-circle">
              <path d="M21 11.5a8.38 8.38 0 0 1-9 8.5 8.5 8.5 0 1 1 9-8.5z"></path>
              <polyline points="8 10 12 14 16 10"></polyline>
            </svg>
            Q&A
          </a>
        </li>

        <li class="py-10px border-b border-borderColor dark:border-borderColor-dark">
          <a href="{% url 'quiz_list' %}"
            class="text-contentColor dark:text-contentColor-dark hover:text-primaryColor dark:hover:text-primaryColor leading-1.8 flex gap-3 text-nowrap">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor"
              stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-message-circle">
              <path d="M21 11.5a8.38 8.38 0 0 1-9 8.5 8.5 8.5 0 1 1 9-8.5z"></path>
              <polyline points="8 10 12 14 16 10"></polyline>
            </svg>
            Testlar ro'yxati
          </a>
        </li>
      </ul>
      {% else %}
      <ul>
        <li
          class="py-10px border-b border-borderColor dark:border-borderColor-dark"
        >
          <a
            href="{% url 'main:student_dashboard' request.user.telegram_id %}"
            class="text-contentColor dark:text-contentColor-dark hover:text-primaryColor dark:hover:text-primaryColor leading-1.8 flex gap-3 text-nowrap"
            ><svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="feather feather-home"
            >
              <path
                d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"
              ></path>
              <polyline points="9 22 9 12 15 12 15 22"></polyline>
            </svg>
            Dashboard</a
          >
        </li>
        <li
          class="py-10px border-b border-borderColor dark:border-borderColor-dark"
        >
          <a
            href="{% url 'accounts:profile' %}"
            class="text-primaryColor hover:text-primaryColor dark:hover:text-primaryColor leading-1.8 flex gap-3 text-nowrap"
            ><svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="feather feather-user"
            >
              <path
                d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"
              ></path>
              <circle cx="12" cy="7" r="4"></circle>
            </svg>
            Mening Profilim</a
          >
        </li>
        <li
          class="py-10px border-b border-borderColor dark:border-borderColor-dark"
        >
          <a
            href="instructor-course.html"
            class="text-contentColor dark:text-contentColor-dark hover:text-primaryColor dark:hover:text-primaryColor leading-1.8 flex gap-3 text-nowrap"
            ><svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="feather feather-monitor"
            >
              <rect
                x="2"
                y="3"
                width="20"
                height="14"
                rx="2"
                ry="2"
              ></rect>
              <line x1="8" y1="21" x2="16" y2="21"></line>
              <line x1="12" y1="17" x2="12" y2="21"></line>
            </svg>
            Mening Kurslarim</a
          >
        </li>
      </ul>
      {% endif %}
      <!-- user -->
      <h5
        class="text-sm leading-1 font-semibold uppercase text-contentColor dark:text-contentColor-dark bg-lightGrey5 dark:bg-whiteColor-dark p-10px pb-7px mt-5 mb-10px"
      >
        USER
      </h5>
      <ul>
        <li
          class="py-10px border-b border-borderColor dark:border-borderColor-dark"
        >
          <a
            href="{% url 'accounts:profile_change' %}"
            class="text-contentColor dark:text-contentColor-dark hover:text-primaryColor dark:hover:text-primaryColor leading-1.8 flex gap-3 text-nowrap"
            ><svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="feather feather-settings"
            >
              <circle cx="12" cy="12" r="3"></circle>
              <path
                d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"
              ></path>
            </svg>
            Sozlamalar</a
          >
        </li>

        <li
          class="py-10px border-b border-borderColor dark:border-borderColor-dark"
        >
          <a
            href="{% url 'accounts:logout' %}"
            class="text-contentColor dark:text-contentColor-dark hover:text-primaryColor dark:hover:text-primaryColor leading-1.8 flex gap-3 text-nowrap"
            ><svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="feather feather-volume-1"
            >
              <polygon
                points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"
              ></polygon>
              <path d="M15.54 8.46a5 5 0 0 1 0 7.07"></path>
            </svg>
            Chiqish</a
          >
        </li>
      </ul>
    </div>
  </div>

templates/includes/user_banner.html
{% load static %}
<!-- banner section -->
<section>
    <div class="container-fluid-2">
      <div
        class="bg-naveBlue p-5 md:p-10 rounded-5 flex justify-center md:justify-between items-center flex-wrap gap-2"
      >
        <div
          class="flex items-center flex-wrap justify-center sm:justify-start"
        >
          <div class="mr-5">
            <img
              src="{% static 'assets/images/teacher/user.png' %}"
              alt=""
              class="w-27 h-27 md:w-22 md:h-22 lg:w-27 lg:h-27 rounded-full p-1 border-2 border-darkdeep7 box-content"
            >
          </div>
          <div class="text-whiteColor font-bold text-center sm:text-start">
            <h5 class="text-xl leading-1.2 mb-5px">Salom</h5>
            <h2 class="text-2xl leading-1.24">{{ request.user.get_full_name }}</h2>
          </div>
        </div>
        
      </div>
    </div>
  </section>