config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve 

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('quiz/', include('quiz.urls')),
    path('about/', include('common.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('student/dashboard/<str:telegram_id>/', views.StudentDashboardView.as_view(), name='student_dashboard'),
    path('course/<slug:course_slug>/', views.CourseDetailView.as_view(), name='course_detail'),
    path("course/lesson/<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/", views.LessonDetailView.as_view(), name="lesson_detail"),
    path('qa/admin/', views.QuestionAnswerAdmin.as_view(), name='qaAdmin'),
    path('question/delete/<int:question_id>/', views.delete_question, name='delete_question'),
    path('answer/to/question/<int:question_id>/', views.AnswerTheQuestion.as_view(), name='answer_to_question'),
    path('rating/', views.RatingView.as_view(), name='rating'),
    path("assignments/<slug:course_slug>/<slug:module_slug>", views.FileLessonView.as_view(), name="assignments")
]

quiz/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('quiz-list/', views.QuizListView.as_view(), name="quiz_list"),
    path('<slug:course_slug>/<int:quiz_id>/', views.MyQuizView.as_view(), name="my_quiz"),
    path('quiz-details/<slug:course_slug>/<int:quiz_id>/', views.MyQuizDetailView.as_view(), name="quiz_details"),
    path('add/questions/<quiz_id>/', views.CreateQuestionView.as_view(), name='add_questions')
]

quiz/models.py
from django.db import models
from django.core.validators import MaxLengthValidator, MinValueValidator
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
import random
from ckeditor_uploader.fields import RichTextUploadingField

from common.models import BaseModel
from main.models import Lesson
from accounts.models import User

class MyQuiz(BaseModel):
    QUIZ_TYPE_CHOICES = (
        (1, _("Pre-course assessment")),
        (2, _("Midterm Exam")),
        (3, _("Final Exam")),
        (4, _("Lesson"))
    )

    title = models.CharField(max_length=150, unique=True)
    quiz_pass = models.FloatField(default=60, 
                                    help_text="testdan o'tish foizi")
    duration_time = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        default=1,
        verbose_name=_("Duration time"),
        help_text=_("minutes")
    )
    attempts_allowed = models.IntegerField(help_text="Testni necha marta yechishga ruxsat beriladi", verbose_name=_("attemps allowed"))
    number_of_questions = models.IntegerField(default=1, verbose_name=_("number of questions"))
    is_available = models.BooleanField(default=False)
    lesson = models.OneToOneField(Lesson, on_delete=models.CASCADE, null=True, blank=True, verbose_name = _("lesson"))
    is_open = models.BooleanField(default=False)
    is_started = models.BooleanField(default=False, verbose_name=_("is started"))
    is_show_selected_ans = models.BooleanField(default=False, verbose_name=_("show selected answers"))
    quiz_type = models.PositiveIntegerField(choices=QUIZ_TYPE_CHOICES, default=4)

    def __str__(self):
        return self.title
    
    def get_url(self):
        # return reverse('my_quiz', kwargs={"course_slug": self.lesson.module.course.slug, "quiz_id":self.id})
        if self.lesson and self.lesson.module and self.lesson.module.course:
            course_slug = self.lesson.module.course.slug
        else:
            
            course_slug = "assessment"

        return reverse('my_quiz', kwargs={
            "course_slug": course_slug,
            "quiz_id": self.id
        })
    
    @property
    def get_questions(self):
        questions = Question.objects.filter(quiz = self, is_available = True)
        questions = list(questions)
        try:
            questions = random.sample(questions, self.number_of_questions)
            return questions
        except Exception as e:
            return None
    
class Question(BaseModel):
    name = RichTextUploadingField()
    quiz = models.ForeignKey(MyQuiz, on_delete=models.CASCADE)
    is_multiple_choice = models.BooleanField(default=False, verbose_name=_("is multiple choice"))
    is_available = models.BooleanField(default=True, verbose_name=_("is available"))
    mark = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.name
    
    @property
    def get_answers(self):
        answers = Answer.objects.filter(question = self)
        answers = list(answers)
        random.shuffle(answers)
        return answers
    
    def get_mark(self, question):
        correct_answers_count = Answer.objects.filter(question = question, is_correct = True).count()
        if correct_answers_count == 0:
            return 1
        mark = self.mark / correct_answers_count
        return mark


class Answer(BaseModel):
    name = models.CharField(max_length=150, verbose_name=_("name"))
    is_correct = models.BooleanField(default=False, verbose_name=_("is correct"))
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name=_("question"))

    def __str__(self):
        return self.name
    
class UserAttempt(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_("user"))
    test = models.ForeignKey(MyQuiz, on_delete=models.CASCADE, related_name="user_attempts", verbose_name=_("test"))
    score = models.DecimalField(max_digits=10, decimal_places=2, verbose_name=_("score"))
    time_taken = models.DurationField(_("time taken"))
    date_taken = models.DateTimeField(auto_now_add=True, verbose_name=_("date taken"))
    is_started = models.BooleanField(default=False, verbose_name=_('is started'))
    is_completed = models.BooleanField(default=False, verbose_name=_('is completed'))

    def __str__(self):
        return f"{self.user.get_full_name()}-{self.test.title}"
    
    @property
    def get_time_taken(self):
        total_seconds = self.time_taken.total_seconds()
        minutes = int(total_seconds // 60)
        seconds = int(total_seconds % 60)
        return f"{minutes} minut {seconds} sekund"
    
    @property
    def get_total(self):
        total = round(self.score * 100 / self.test.number_of_questions, 2)
        return total

class Result(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(MyQuiz, on_delete=models.SET_NULL, null=True, blank=True)
    total_questions = models.PositiveIntegerField()
    correct_questions = models.DecimalField(max_digits=10, decimal_places=2)
    is_pass = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.get_full_name}"
    
    @property
    def get_percentage(self):
        return round((self.correct_questions * 100 / self.total_questions), 2)


class UserAnswer(BaseModel):
    attempt = models.ForeignKey(UserAttempt, related_name="user_answers", on_delete=models.CASCADE, verbose_name=_("attempt"))
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name=_("question"))
    selected_answers = models.ManyToManyField(Answer, verbose_name=_("selected answers"))

    def __str__(self):
        return f"{self.question.name}-{self.attempt.score}"

quiz/forms.py
from django import forms

class QuestionsAddForm(forms.Form):
    questions = forms.CharField(
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'rows': 20,
            'placeholder': """# savol matni
+to'g'ri javob
-javob 2
-javob 3
-javob 4
===
# savol matni
+to'g'ri javob
-javob 2
-javob 3
-javob 4
===
....""",
            'style': 'width:100%; border:1px solid #ccc; border-radius:8px; padding:10px; font-size:14px;'
        })
    )

quiz/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
import random
from django.http import HttpResponse
from main.models import *
from django.contrib import messages
from django.utils import timezone
from django.db import transaction
from django.core.cache import cache
from .forms import QuestionsAddForm
from django import http

from .models import *

class QuizListView(LoginRequiredMixin, View):
    def get(self, request):
        tests = MyQuiz.objects.filter(is_available = True)
        context = {
            'tests': tests
        }
        return render(request, 'quiz/quiz-list.html', context)
    
class CreateQuestionView(LoginRequiredMixin, View):
    def get(self, request, quiz_id):
        form = QuestionsAddForm()
        return render(request, 'quiz/add-questions.html', {'form':form})
    
    def post(self, request, quiz_id):
        test = get_object_or_404(MyQuiz, id = quiz_id)
        form = QuestionsAddForm(request.POST)
        if form.is_valid():
            questions_data = form.cleaned_data['questions']
            try:
                questions_answers = questions_data.strip().split('===')
                
                for block in questions_answers:  
                    lines = block.strip().split("\n")
                    question_text = lines[0].lstrip('#') 
                    
                    question = Question.objects.create(
                        quiz = test,
                        name = question_text
                    )
                    
                    for line in lines[1:]:
                        is_correct = line.startswith("+")  
                        answer_text = line[1:].strip() 
                        Answer.objects.create(
                            question = question, 
                            name = answer_text,
                            is_correct = is_correct
                        )

                messages.success(request, "Savollar muvaffaqiyatli qo'shildi!")
                return redirect('add_questions', test.id)
            except Exception as e:
                messages.error(request, f"Xato yuz berdi: {e}")
                # return render(request, 'quiz/add-questions.html', {'form':form})
                return http.HttpResponse(form)

class MyQuizDetailView(LoginRequiredMixin, View):
    def get(self, request, course_slug, quiz_id):
        quiz = get_object_or_404(MyQuiz, id = quiz_id)
        results = Result.objects.filter(quiz = quiz, user = request.user)
        context = {
            'quiz':quiz,
            'results':results,
        }
        return render(request, "quiz/quiz-detail.html", context)

class MyQuizView(LoginRequiredMixin, View):
    def get(self, request, course_slug, quiz_id):
        quiz = get_object_or_404(MyQuiz, id = quiz_id)
        questions = quiz.get_questions
        

        if cache.get(f"{request.user.telegram_id}_{quiz.id}_questions") is None:
            cache.set(f"{request.user.telegram_id}_{quiz.id}_questions", questions, timeout=60*quiz.duration_time + 30)
        cached_questions = cache.get(f"{request.user.telegram_id}_{quiz.id}_questions")

        attempt_count = UserAttempt.objects.filter(user = request.user, test = quiz, is_completed = True).count()
        if attempt_count >= quiz.attempts_allowed:
            messages.error(request, f"Testga {quiz.attempts_allowed} marta urinish berilgan sizning urinishingiz tugadi.")
            return redirect('quiz_details', quiz.lesson.module.course.slug, quiz.id)
        
        user_attempt, created = UserAttempt.objects.get_or_create(
            user = request.user,
            test = quiz,
            score = 0,
            time_taken = timezone.timedelta(0),
            is_started = True
        )
        
        context = {
            "questions":cached_questions,
            "quiz":quiz,
            "question_count":len(cached_questions),
        }
        return render(request, "quiz/questions.html", context)

    def post(self, request, course_slug, quiz_id):
        try:
            quiz = get_object_or_404(MyQuiz, id = quiz_id)
            questions = Question.objects.filter(quiz = quiz)
            attempt = UserAttempt.objects.filter(user = request.user, test = quiz, is_completed = False).last()
            with transaction.atomic():
                score = 0
                overall_score = 0
                cached_questions = cache.get(f"{request.user.telegram_id}_{quiz.id}_questions")
                for i in cached_questions:
                    overall_score += i.mark
    

                for question in cached_questions:
                    if question.is_multiple_choice:

                        selected_answer_ids = request.POST.getlist(f"question_{question.id}")
                        
                        if selected_answer_ids:
                            for ans_id in selected_answer_ids:
                                answer = get_object_or_404(Answer, id = int(ans_id))
                                if answer.is_correct:
                                    score += answer.question.get_mark(question=question)

                            user_answer = UserAnswer.objects.create(
                                attempt = attempt,
                                question = question,
                            )
                            user_answer.selected_answers.add(*map(int, selected_answer_ids))
                    else:
                        selected_answer_id = request.POST.get(f"question_{question.id}")
                        if selected_answer_id:
                            answer = get_object_or_404(Answer, id = int(selected_answer_id))
                            if answer.is_correct:
                                score += answer.question.get_mark(question=question)
                            

                            user_answer = UserAnswer.objects.create(
                                attempt = attempt,
                                question = question,
                            )
                            user_answer.selected_answers.add(int(selected_answer_id))
                attempt.is_completed = True
                attempt.time_taken = timezone.now() - attempt.created
                attempt.score = score
                attempt.save()

                
                result = (score / overall_score) * 100
                is_pass = False
                if result >= quiz.quiz_pass:
                    is_pass = True
            if is_pass:
                lesson = Lesson.objects.get(slug = quiz.lesson.slug)
                next_lesson = Lesson.objects.filter(module = lesson.module, id__gt=lesson.id).order_by('id').first()
                if next_lesson:
                    next_progress, created = UserLessonProgress.objects.get_or_create(
                        user = request.user,
                        lesson = next_lesson,
                        course = Course.objects.get(slug = course_slug)
                    )
                    next_progress.is_open = True
                    next_progress.save()

            Result.objects.create(
                user = request.user,
                quiz = quiz,
                total_questions = len(cached_questions),
                correct_questions = score,
                is_pass = is_pass
            )
            cache.delete(f"{request.user.telegram_id}_{quiz.id}_questions")
            return redirect('quiz_details', quiz.lesson.module.course.slug, quiz.id)
        except Exception as e:
            raise Exception(f"Xatolik! {e}")

templates/quiz/add-questions.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %} Profile | {{ profile.get_full_name }} {% endblock %}

{% block content %}
<main class="bg-transparent">
    {% include 'includes/user_banner.html' %}

    <!--dashbord menu section -->
    <section>
        <div class="container-fluid-2">
            <div class="grid grid-cols-1 lg:grid-cols-12 gap-30px pt-30px pb-100px">
                {% include 'includes/profile_left.html' %}
                <!-- dashboard content -->
                <div class="lg:col-start-4 lg:col-span-9">
                    <!-- profile details -->
                    <div
                        class="p-10px md:px-10 md:py-50px mb-30px bg-whiteColor dark:bg-whiteColor-dark shadow-accordion dark:shadow-accordion-dark rounded-5">
                        <div class="mb-6 pb-5 border-b-2 border-borderColor dark:border-borderColor-dark">
                            <h2 class="text-2xl font-bold text-blackColor dark:text-blackColor-dark">
                                Savol qo'shish
                            </h2>
                        </div>

                        <!-- content -->
                        <div class="lg:col-start-4 lg:col-span-9">
                            <!-- quize attempts area -->
                            <div
                                class="p-10px md:px-10 md:py-50px mb-30px bg-whiteColor dark:bg-whiteColor-dark shadow-accordion dark:shadow-accordion-dark rounded-5">
                               

                                <hr class="my-4 border-contentColor opacity-35">

                                <!-- main content -->
                                 {{ form.errors }}
                                <div class="overflow-auto">
                                    <form action="" method="post">
                                        {% csrf_token %}
                                        {{ form.questions }}
                                        <button type="submit" class="btn btn-outline-success mt-3">Yuborish</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock %}

templates/quiz/questions.html
{% extends 'base.html' %}

{% block title %} {{ lesson.title }} {% endblock %}

{% block content %}
<main class="bg-transparent">
  <!-- quiz section -->
  <section>
    <div class="container-fluid-2 py-100px">
      <div class="grid grid-cols-1 xl:grid-cols-12 gap-30px">
        {% include 'includes/lesson-left.html'%}
        <!-- quiz right -->
        <div class="xl:col-start-5 xl:col-span-8 relative" data-aos="fade-up">

          <div>
            <ul class="flex flex-wrap items-center gap-x-1">
              <li class="text-bodyColor dark:text-bodyColor-dark leading-1.8">
                <h1><div id="timer" style="font-size: 24px;"></div></h1>
              </li>
            </ul>
          </div>
          <!-- question 1 -->
          <form id="testForm" action="" method="post">
            {% csrf_token %}
            {% for question in questions %}
            <div>
              <hr class="border-borderColor2 dark:opacity-30 my-4">
              <h4
                class="text-2xl sm:text-size-28 font-bold leading-1.2 text-blackColor dark:text-blackColor-dark mb-15px">
                {{ forloop.counter }}. {{ question.name|safe }}
              </h4>
              <ul class="grid grid-cols-1 md:grid-cols-2 gap-y-0.5 gap-x-30px">
                {% for answer in question.answer_set.all %}
                <li class="flex items-center gap-x-2">
                  {% if question.is_multiple_choice %}
                  <input
                    class="relative w-4 h-4 z-0 rounded after:absolute after:w-4 after:h-4 after:left-0 after:top-0 block after:-z-1 after:rounded after:focus:shadow-select box-content"
                    type="checkbox" value="{{ answer.id }}" id="{{ answer.id }}" name="question_{{ question.id }}">
                  {% else %}
                  <input
                    class="relative w-4 h-4 z-0 rounded after:absolute after:w-4 after:h-4 after:left-0 after:top-0 block after:-z-1 after:rounded after:focus:shadow-select box-content"
                    type="radio" value="{{ answer.id }}" id="{{ answer.id }}" name="question_{{ question.id }}">
                  {% endif %}

                  <label for="{{ answer.id }}" class="text-bodyColor dark:text-bodyColor-dark leading-1.8">
                    {{ answer.name }}
                  </label>
                </li>
                <br>
                {% endfor %}
              </ul>
              <br>
              <br>
              <br>
            </div>
            {% endfor %}
            <div>
              <button type="submit"
                class="text-size-15 text-whiteColor bg-primaryColor px-25px py-10px border border-primaryColor hover:text-primaryColor hover:bg-whiteColor inline-block rounded group dark:hover:text-whiteColor dark:hover:bg-whiteColor-dark">
                Testni tugatish <i class="icofont-long-arrow-right"></i>
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</main>

<script>
    var countdown;
    var timerElement = document.getElementById("timer");

    function updateTimer() {
        var minutes = Math.floor(countdown / 60);
        var seconds = countdown % 60;
        timerElement.innerHTML = "<b>Test Tugashiga: </b><span style='color:#7ccb11; font-weight:bold;'>" 
    + minutes + ":" + (seconds < 10 ? "0" : "") + seconds + "</span><b> vaqt qoldi</b>";

    }

    function submitFormOnTimeout() {
        // Formni yuborishdan oldin localStorage vaqtini o'chirish
        localStorage.removeItem("quiz_start_time");
        document.getElementById("testForm").submit();
    }

    function startTimer() {
        var initialStartTime = localStorage.getItem("quiz_start_time");
        if (!initialStartTime) {
            // Agar localStorage'da vaqt topilmasa, yangi vaqtni saqlash
            localStorage.setItem("quiz_start_time", new Date().toISOString());
            initialStartTime = localStorage.getItem("quiz_start_time");
        }

        countdown = Math.max(60 * {{ quiz.duration_time }} - Math.floor((new Date() - new Date(initialStartTime)) / 1000), 0);

        var timer = setInterval(function () {
            updateTimer();
            countdown--;

            if (countdown < 0) {
                clearInterval(timer);
                submitFormOnTimeout();
            }
        }, 1000);

        // Yakunlash tugmasi bosilganda localStorage o'chirilsin
        document.getElementById("submitBtn").addEventListener("click", function () {
            localStorage.removeItem("quiz_start_time");
        });
    }

    window.onload = startTimer;
</script>
{% endblock %}

templates/quiz/quiz-list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Profile | {{ profile.get_full_name }} {% endblock %}

{% block content %}
<main class="bg-transparent">
    {% include 'includes/user_banner.html' %}

    <!--dashbord menu section -->
    <section>
        <div class="container-fluid-2">
            <div class="grid grid-cols-1 lg:grid-cols-12 gap-30px pt-30px pb-100px">
                {% include 'includes/profile_left.html' %}
                <!-- dashboard content -->
                <div class="lg:col-start-4 lg:col-span-9">
                    <!-- profile details -->
                    <div
                        class="p-10px md:px-10 md:py-50px mb-30px bg-whiteColor dark:bg-whiteColor-dark shadow-accordion dark:shadow-accordion-dark rounded-5">
                        <div class="mb-6 pb-5 border-b-2 border-borderColor dark:border-borderColor-dark">
                            <h2 class="text-2xl font-bold text-blackColor dark:text-blackColor-dark">
                                Testlar Ro'yxati
                            </h2>
                        </div>

                        <!-- content -->
                        <div class="lg:col-start-4 lg:col-span-9">
                            <!-- quize attempts area -->
                            <div
                                class="p-10px md:px-10 md:py-50px mb-30px bg-whiteColor dark:bg-whiteColor-dark shadow-accordion dark:shadow-accordion-dark rounded-5">
                                <!-- heading -->
                                <div class="mb-6 pb-5 border-b-2 border-borderColor dark:border-borderColor-dark">
                                    <h2 class="text-2xl font-bold text-blackColor dark:text-blackColor-dark">
                                        Testlar ro'yxati
                                    </h2>
                                </div>

                                <hr class="my-4 border-contentColor opacity-35">
                                <!-- main content -->
                                <div class="overflow-auto">
                                    <table class="w-full text-left text-nowrap">
                                        <thead
                                            class="text-sm md:text-base text-blackColor dark:text-blackColor-dark bg-lightGrey5 dark:bg-whiteColor-dark leading-1.8 md:leading-1.8">
                                            <tr>
                                                <th class="px-5px py-10px md:px-5">Test</th>
                                                <th class="px-5px py-10px md:px-5">O'tish bali</th>
                                                <th class="px-5px py-10px md:px-5">Urinishlar</th>
                                                <th class="px-5px py-10px md:px-5">Savollar</th>
                                                <th class="px-5px py-10px md:px-5">Test turi</th>
                                                <th class="px-5px py-10px md:px-5"></th>
                                            </tr>
                                        </thead>
                                        <tbody
                                            class="text-size-13 md:text-base text-contentColor dark:text-contentColor-dark font-normal">
                                            {% for test in tests %}
                                            <tr class="leading-1.8 md:leading-1.8">
                                                <th class="px-5px py-10px md:px-5 font-normal text-wrap">
                                                    <p>{{ test.created }}</p>
                                                    <span class="text-blackColor dark:text-blackColor-dark font-bold">{{ test.title }}</span>
                                                </th>
                                                <td class="px-5px py-10px md:px-5">
                                                    <p>{{ test.quiz_pass }}</p>
                                                </td>
                                                <td class="px-5px py-10px md:px-5">
                                                    <p>{{ test.attempts_allowed }}</p>
                                                </td>
                                                <td class="px-5px py-10px md:px-5">
                                                    <p>{{ test.number_of_questions }}</p>
                                                </td>
                                                <td class="px-5px py-10px md:px-5">
                                                    <p class="text-xs">
                                                        <span
                                                            class="h-22px inline-block px-7px bg-greencolor2 leading-22px font-bold text-whiteColor rounded-md">
                                                            {{ test.get_quiz_type_display }}</span>
                                                    </p>
                                                </td>
                                                <td class="px-5px py-10px md:px-5">
                                                    <div class="dashboard__button__group">
                                                        <a class="flex items-center gap-1 text-sm font-bold text-whiteColor hover:text-primaryColor bg-primaryColor hover:bg-whiteColor dark:hover:bg-whiteColor-dark border border-primaryColor h-30px w-full px-14px leading-30px justify-center rounded-md my-5px"
                                                            href="{% url 'add_questions' test.id %}">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="14"
                                                                height="24" viewBox="0 0 24 24" fill="none"
                                                                stroke="currentColor" stroke-width="2"
                                                                stroke-linecap="round" stroke-linejoin="round"
                                                                class="feather feather-plus-circle">
                                                                <circle cx="12" cy="12" r="10"></circle>
                                                                <line x1="12" y1="8" x2="12" y2="16"></line>
                                                                <line x1="8" y1="12" x2="16" y2="12"></line>
                                                            </svg>
                                                            Savol qo'shish
                                                        </a>
                                                    </div>

                                                </td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock %}